### ISSUE TITLE
Webpack function config is not called with CLI arguments

### ISSUE THREAD

**Issue by Demivan** [webpack-contrib/config-loader#11]
In https://github.com/webpack-contrib/config-loader#gotchas it is specified that webpack function will be called with `argv` parameter, but it does not actually work. There is related issue webpack-contrib/webpack-command#23.

* Operating System: Windows 10
* Node Version: 9.11.1
* NPM Version: 5.6.0
* webpack Version: 4.10.0
* config-loader Version: 1.0.0

### Expected Behavior

Function should be called with arguments passed to CLI.

### Actual Behavior
Function is called without arguments.

### Code

```js
module.exports = function (argv) {
  const production = argv.mode === 'production'
  ...
}
```

### How Do We Reproduce?

Export function from webpack config that uses argv parameter.

**Comment by shellscape** [comment]
Thanks for the issue :beer:

Should have a fix out in a few minutes.

**Comment by shellscape** [comment]
v1.1.3 published
