### ISSUE TITLE
Is rules filtering backward?

### ISSUE THREAD

**Issue by jods4** [webpack-contrib/config-loader#17]
* Operating System: Win 10
* Node Version: 10.3.0
* Yarn Version: 1.7.0
* webpack Version: 4.16.5
* config-loader Version: 1.2.1

### Expected Behavior

When I extend a base config with a duplicate `module.rules[].test`, my intention is to replace the base one with different options.

So I'm expecting the default filter to keep _the last_ appended `rule` for any given `test`.

### Actual Behavior

The filter keeps _the first_ `rule` for any given `test`. 
This happens to be the one from the _base_ config, so my _extensions_ are basically discarded.

Culprit is here:
https://github.com/webpack-contrib/config-loader/blob/master/lib/filters/rules.js#L23

Rules are added in-order, if they are not already inside the final array.

### Code

```js
// config-a.js
module.exports = {
 module: {
    rules: [ { test: /\.html$/i, use: 'loader-a' } ]
  }
};

// config-b.js
module.exports = {
  extends: path.resolve("config-a.js"),
  module: {
    rules: [ { test: /\.html$/i, use: 'loader-b' } ]
  }
};

// Resulting config is same as config-a, expected config-b.
```

**Comment by jods4** [comment]
Suggested fix if you agree the behavior should be changed:
```js
//    return rules.reduce(
    return rules.reduceRight(
      (array, other) =>
        array.findIndex(
          (rule) =>
            rule.test === other.test || regexEqual(rule.test, other.test)
        ) < 0
//          ? [...array, other]
          ? [other, ...array]
          : array,
      []
    );
```

**Comment by evilebottnawi** [comment]
Package was deprecated. `webpack-command` are also deprecated. Please use `webpack-cli`. If any features were not implemented in `webpack-cli` feel free to create issue. 

Why deprecated `webpack-command` ?
- `webpack-cli` is very stable and have more features.
- Two CLIs are misleading for developers.
- Hard to maintain two package with same purpose.
- The author stopped developing the package.
- Most of the features are already implemented in `webpack-cli`.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
